name: smile_detection_template
description: A Flutter starter template for building smile detection games and apps using ML Kit and Supabase.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  google_mlkit_face_detection: ^0.10.0
  supabase_flutter: ^1.10.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_linter: ^3.0.0

flutter:
  uses-material-design: true
